/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Asignacion_Aula1;
import io.javalin.Javalin;

public class App {

    public static void main(String[] args) {
        Javalin app = Javalin.create().start(7000);
        app.before("/", ctx -> {
            ctx.sessionAttribute("Usuario", "usr");
            ctx.sessionAttribute("Contrasena", "pass");
        });
    }
}
